# Install python and related modules then run a test

name: Mid plane heat flux

on: [commit]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies and run
      run: |
        python -m pip install --upgrade pip
        pip install scipy numpy matplotlib mayavi
        export PYTHONPATH=modules
        python3 tests/test1a-LFS-midplane.py   
