# Install python and related modules then run a test

name: Mid plane heat flux

on: [push]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run
      run: |
        sudo apt-get update
        sudo apt-get install python3.6
        python3 -m pip install --upgrade pip --user vtk scipy numpy matplotlib mayavi
        export PYTHONPATH=modules
        python3 tests/test1a-LFS-midplane.py   
