name: Mid plane heat flux

on: [push]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Token
      env: | 
         token: '${{ secrets.GITHUB_TOKEN }}'
      run: |
        echo "AAAA $token"
        
    - name: Download
      uses: actions/checkout@v2
    
    - name: Install
      run: |
        sudo apt update  -qq
        sudo apt install -qq python-configobj tree
        mkdir -p out
        tree
        python3 -m pip install --upgrade pip --user vtk scipy numpy matplotlib 
    
    - name: Run
      run: |
        export PYTHONPATH=modules
        python3 tests/2Dprojections/test1a-LFS-midplane.py out/test1a-LFS-midplane.svg
    
    - name: Upload 
      env: | 
         token: '${{ secrets.GITHUB_TOKEN }}'
      run: |
        tree
        github/uploadOut.perl out/ out/  $token
        
        
   
