# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Mid plane heat flux

on:
  commit:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies and run
      run: |
        python -m pip install --upgrade pip
        pip install scipy numpy matplotlib mayavi
        export PYTHONPATH=modules
        python3 tests/test1a-LFS-midplane.py   
